services:
  # PostgreSQL database
  postgres:
    image: postgres:14
    container_name: gdelt-postgres
    hostname: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: gdelt
      POSTGRES_USER: flink_user
      POSTGRES_PASSWORD: flink_pass
    command:
      - "postgres"
      - "-c"
      - "wal_level=logical"
      - "-c"
      - "max_wal_senders=10"
      - "-c"
      - "max_replication_slots=10"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres/init:/docker-entrypoint-initdb.d
      - ./data:/data:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U flink_user -d gdelt"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      flink-network:
        aliases:
          - gdelt-postgres

  # Flink job manager (master)
  jobmanager:
    user: "0:0"
    image: flink:1.18-scala_2.12
    container_name: flink-jobmanager
    hostname: jobmanager
    ports:
      - "8081:8081"
    command: jobmanager
    volumes:
      - ./flink/lib/flink-sql-connector-postgres-cdc-2.4.2.jar:/opt/flink/lib/flink-sql-connector-postgres-cdc-2.4.2.jar
      - ./flink/lib/postgresql-42.7.1.jar:/opt/flink/lib/postgresql-42.7.1.jar
      - ./flink/sql:/opt/flink/sql:ro
      - ./flink/conf/flink-conf.yaml:/opt/flink/conf/flink-conf.yaml:ro
      - ./flink/lib/flink-connector-jdbc-3.1.2-1.18.jar:/opt/flink/lib/flink-connector-jdbc-3.1.2-1.18.jar
    networks:
      - flink-network
    healthcheck:
      test: ["CMD-SHELL", "bash -lc 'echo > /dev/tcp/127.0.0.1/8081'"]
      interval: 10s
      timeout: 5s
      retries: 20
      start_period: 15s
    depends_on:
      postgres:
        condition: service_healthy

  # Flink task manager (worker)
  taskmanager:
    user: "0:0"
    image: flink:1.18-scala_2.12
    container_name: flink-taskmanager
    hostname: taskmanager
    command: taskmanager
    volumes:
      - ./flink/lib/flink-sql-connector-postgres-cdc-2.4.2.jar:/opt/flink/lib/flink-sql-connector-postgres-cdc-2.4.2.jar
      - ./flink/lib/postgresql-42.7.1.jar:/opt/flink/lib/postgresql-42.7.1.jar
      - ./flink/conf/flink-conf.yaml:/opt/flink/conf/flink-conf.yaml:ro
      - ./flink/lib/flink-connector-jdbc-3.1.2-1.18.jar:/opt/flink/lib/flink-connector-jdbc-3.1.2-1.18.jar
    networks:
      - flink-network
    depends_on:
      - jobmanager

volumes:
  postgres_data:

networks:
  flink-network:
    driver: bridge
